/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HumanAddr = string;

/**
 * Instantiation message
 */
export interface InitMsg {
    /**
     * prng entropy
     */
    entropy: string;
    /**
     * card contract info
     */
    token_contract: ContractInfo;

}
/**
 * code hash and address of a contract
 */
export interface ContractInfo {
    /**
     * contract's address
     */
    address: HumanAddr;
    /**
     * contract's code hash string
     */
    code_hash: string;

}


/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type QueryMsg = {
    config: {

    };

};

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Responses from queries
 */
export type QueryAnswer = {
    config: {
        minting_has_halted: boolean;

    };

};

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Handle messages
 */
export type HandleMsg =
    | {
        mint: {
            description: string;
            fullres: string;
            thumbnail: string;
            /**
             * names to give the cards.  Must provide 3 names
             */
            title: string;

        };

    }
    | {
        change_admin: {
            /**
             * address with admin authority
             */
            address: HumanAddr;

        };

    }
    | {
        set_mint_status: {
            /**
             * true if minting should be halted
             */
            stop: boolean;

        };

    }
    | {
        new_token_contract: {
            /**
             * new card ContractInfo
             */
            token_contract: ContractInfo;

        };

    };

/**
* code hash and address of a contract
*/
export interface ContractInfo {
    /**
     * contract's address
     */
    address: HumanAddr;
    /**
     * contract's code hash string
     */
    code_hash: string;
  
}

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Responses from handle functions
 */
export type HandleAnswer =
    | {
        mint: {
            status: ResponseStatus;

        };

    }
    | {
        change_admin: {
            new_admin: HumanAddr;

        };

    }
    | {
        set_mint_status: {
            minting_has_halted: boolean;

        };

    }
    | {
        new_card_contract: {
            token_contract: HumanAddr;

        };

    };
/**
* success or failure response
*/
export type ResponseStatus = "Success" | "Failure";
